### ISSUE TITLE
ClusterForm: Recurse over nested relationships

### ISSUE THREAD

**Issue by Sam-Costigan** [wagtail/django-modelcluster#105]
This relates to the following issue with wagtail: https://github.com/wagtail/wagtail/issues/1952

When `ClusterFormMetaclass.__new__()` is called, it iterates over child relations for the given model and creates a `Formset` class by calling the factory function `childformset_factory`. The form created by the factory function is a subclass of django's base `ModelForm`, which means that `ClusterFormMetaclass` isn't used for those forms. If the factory function were to subclass from `ClusterForm` instead, then `ClusterFormMetaclass.__new__()` would be called recursively and `Formset` classes would be created for nested relationships.

It would then be the responsibility of `ClusterForm` to recurse over nested relationships on form initialisation and save. This would allow for creating nested models in wagtail using `InlinePanel`s, a feature that I would love to see implemented.

Is this something you would be willing to consider?

**Comment by gasman** [comment]
Hi @Sam-Costigan,
I'd absolutely be in favour of this - many thanks for tracking down the root cause. If you're willing to create a PR with this change (including tests to confirm that nested formsets are working as expected) then I'd be very happy to accept it.

**Comment by Sam-Costigan** [comment]
Thanks @gasman, I'll try to get a PR up over the next week or so for review.

**Comment by gasman** [comment]
Completed in #106
