### ISSUE TITLE
Nested OneToMany relationship results in 3 empty forms in wagtail admin

### ISSUE THREAD

**Issue by wfcarlson** [wagtail/django-modelcluster#113]
I have some Wagtail models that look like this:

events.models.py:

```
from django.db import models
from wagtail.core.models import Page, Orderable
from modelcluster.models import ClusterableModel
from wagtail.admin.edit_handlers import InlinePanel

class Event(Page):
    ...
    content_panels = Page.content_panels + [
        InlinePanel('event_presentations'),
    ]

class Presentation(Orderable, ClusterableModel):
    event = ParentalKey('events.Event', related_name='event_presentations')
    ...

    panels = [
                InlinePanel('presentation_dates', label='Presentation date times'
    ]

class PresentationDate(models.Model):
    presentation = ParentalKey('events.Presentations', related_name='presentation_dates', on_delete=models.CASCADE)
    date_time = models.DateTimeField("Presentation date and time")

```

This results in three extra empty 'Presentation Date' forms being present in the admin whenever a Presentation form is created. Changing the `extra_form_count` in the django-modelcluster ClusterFormMetaclass from 3 to 0 seems to fix the problem (django-modelcluster/forms.py line 215). Is there a way to override this value without editing the source code of django-modelcluster?

**Comment by alxbridge** [comment]
I believe this and https://github.com/wagtail/wagtail/issues/5511 are the same issue. The workaround in the [StackOverflow post linked from that issue](https://stackoverflow.com/a/57516105) worked for my occurrence of this problem.

**Comment by gasman** [comment]
Fixed in https://github.com/wagtail/wagtail/pull/5566
