### ISSUE TITLE
Commit method in DeferringRelatedManager deletes related records before adding.

### ISSUE THREAD

**Issue by supermanzer** [wagtail/django-modelcluster#116]
## Summary
When publishing a Page, child pages connected via a `ParentalKey` are deleted prior to being added.  This results in a `Page Not Found` error.  The issue occurs between lines 196 - 207 in `fields.py`
```
     live_items = list(original_manager.get_queryset())
            for item in live_items:
                if item not in final_items:  # <-- Both live_items and final_items point to same page but this returns false
                    item.delete()  # <-- Page deleted

            for item in final_items:
                # Django 1.9+ bulk updates items by default which assumes
                # that they have already been saved to the database.
                # Disable this behaviour.
                # https://code.djangoproject.com/ticket/18556
                # https://github.com/django/django/commit/adc0c4fbac98f9cb975e8fa8220323b2de638b46
                original_manager.add(item, bulk=False)  # <-- Page does not exist here.
```

### Environment
* Python 3.6
* Django 2.2.4
* django-modelcluster 4.4
* wagtail 2.6.1

### Models
```
class BulkGood(Page):
    ....

        def save(self, **kwargs):
          # clear cached listing template
          cache_key = make_template_fragment_key('bulks')
          cache.delete(cache_key)
          # Update our title and slug fields based on our name
          self.title = self.name
          self.slug = slugify(self.name)
          return super().save(**kwargs)


class FinishedGood(Page):
    ....
   bulk = ParentalKey(
        'faqs.BulkGood',
        related_name='bulk_products',
        null=True, blank=True,
        on_delete=models.SET_NULL,
    )
    ....
```

Please let me know if there are any further details required or perhaps a more "proper" way to relate these entities.

**Comment by gasman** [comment]
Hi @supermanzer,
I'm 99% sure the `ParentalKey` on `FinishedGood` should be a `ForeignKey` instead. ParentalKey implies that `FinishedGood` is contained _within_ the data model of `BulkGood` - i.e. you'll edit a `BulkGood` and a set of `FinishedGood`s as a single unit, and when you save a revision of a `BulkGood` page you'll save all the related `FinishedGood`s along with it. And if that's the case, it probably doesn't make sense for `FinishedGood` to be a `Page`...

If you do have specific reasons for this to be a ParentalKey, please give further details and I'll be happy to reopen.
