### ISSUE TITLE
When I Modify Elements via Admin Panel , Its not getting Saved

### ISSUE THREAD

**Issue by vmwsree** [wagtail/django-modelcluster#140]
I am using filter_horizontal widget on my manytomany relation, The current model when i update using admin interface it is not getting updated. Shell commands works

**Comment by gasman** [comment]
Hi @vmwsree,
This does not give us enough information to diagnose the problem, sorry. Please feel free to open a new issue with full steps to reproduce the problem, including the complete model / form code.
