### ISSUE TITLE
test suite fails with django-taggit >= 2.0.0

### ISSUE THREAD

**Issue by tijuca** [wagtail/django-modelcluster#147]
We've noticed in Debian that django-modellcluster is failing the autopkgtesting in the package since django-taggit was bumped to 2.0.0.

https://ci.debian.net/data/autopkgtest/testing/amd64/p/python-django-modelcluster/17044291/log.gz

This is happen due [test_can_access_tags_on_unsaved_instance](https://github.com/wagtail/django-modelcluster/blob/main/tests/tests/test_tag.py#L40) is using [TaggableManager.set](https://django-taggit.readthedocs.io/en/latest/api.html#TaggableManager.set) which behavior did change in django-taggit 2.x.
I'm not deep into the test suite but my guess is that `TaggableManager.add` is needed here?

The issue in the Debian BTS about that failing test is [#1000684](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1000684).

**Comment by gasman** [comment]
Fixed in #151.
