### ISSUE TITLE
Wagtail 3.0 support planned?

### ISSUE THREAD

**Issue by nicksergeant** [wagtail/django-modelcluster#164]
Just checking to see if there are plans to update this application to be compatible with Wagtail 3.0? I'm working on testing my Wagtail installations with 3.0rc3 but ran into this being unsupported.

**Comment by gasman** [comment]
django-modelcluster is one of the components Wagtail is built on, so updating it for Wagtail compatibility isn't a meaningful concept.

To run Wagtail 3.0, you'll need to upgrade django-modelcluster to v6.0 - this will happen automatically unless you've pinned it in your project dependencies.
