### ISSUE TITLE
Django 5.0 support

### ISSUE THREAD

**Issue by laymonage** [wagtail/django-modelcluster#169]
Django 5.0 removed `django.utils.timezone.utc`, which is an alias of the built-in `datetime.timezone.utc`, and suggests using the built-in `utc` value directly.

We have two instances of this in the code:

https://github.com/wagtail/django-modelcluster/blob/8666f16eaf23ca98afc160b0a4729864411c0563/modelcluster/models.py#L26-L28

There might be other fixes needed to be done in order to support Django 5.0, but I haven't checked.

See also https://github.com/wagtail/wagtail/issues/9964.

**Comment by gasman** [comment]
Fixed in #167.
