### ISSUE TITLE
Specify django-taggit as an optional dependency via extras_require

### ISSUE THREAD

**Issue by browniebroke** [wagtail/django-modelcluster#67]
The new 3.0 version requires [`django-taggit>=0.20`](https://github.com/wagtail/django-modelcluster/blob/master/modelcluster/contrib/taggit.py#L12) but it's not specified in the install requires section of [`setup.py`](https://github.com/wagtail/django-modelcluster/blob/master/setup.py#L18). 

Since my project doesn't depend directly on taggit, upgrading to 3.0 is breaking my build. Having this requirement in the setup.py would have upgraded the downstream dependency automatically.

Was this a conscious decision or was it forgotten?

**Comment by gasman** [comment]
Hi @browniebroke,

`django-taggit` is an optional dependency of django-modelcluster, and so it isn't specified in setup.py - it's only required if you import `modelcluster.contrib.taggit`. What error are you getting?

**Comment by browniebroke** [comment]
Ok, understood, thanks for your answer. My setup is wrong then, I should explicitly set `django-taggit` as dependency then.

Maybe that could be listed as an `extras_require` then? Example:

```python
setup(
     ...
     extras_require={
         'taggit': ['django-taggit>=0.20'],
    },
    ...
)
```

**Comment by gasman** [comment]
Sure - I think that would be a sensible addition. Thanks for the suggestion!
