### ISSUE TITLE
ParentalManyToManyField.value_from_object fails on unsaved instances on Django 1.10

### ISSUE THREAD

**Issue by gasman** [wagtail/django-modelcluster#69]
In Django 1.10, ManyToManyField.value_from_object always returns an empty set of related objects when passed an instance without a primary key:
https://github.com/django/django/commit/f529d0cb5855db2dfc8d0d39850dbb4793bc75c2

This is not valid for ParentalManyToManyField, since an unsaved instance can have related objects; we should therefore override value_from_object to bypass this test.

**Comment by auvipy** [comment]
now that django 1.11b1 released whats the status?

**Comment by gasman** [comment]
I'd assume that this bug is present on 1.11 too. As far as I'm aware it doesn't affect Wagtail (because the only place I know of which calls `value_from_object` is revision comparison, and that never operates on unsaved objects; I encountered this while writing unit tests for revision comparison, because those tests were invoking the comparison module in a different way to the 'real world' usage). For that reason it hasn't been an urgent one to fix, but it ought to be fixed in order for django-modelcluster to be considered functionally correct.
