### ISSUE TITLE
RemovedInDjango20Warning: Usage of field.rel has been deprecated. Use field.remote_field instead.

### ISSUE THREAD

**Issue by coredumperror** [wagtail/django-modelcluster#80]
When using `python -Wd manage.py test` on my codebase, to try to ferret out any changes I need to make in my own code for forward compatibility, I discovered that modelcluster throws this deprecation warning three times, all in `fields.py` (twice on line 257, once on 270):

```
RemovedInDjango20Warning: Usage of field.rel has been deprecated. Use field.remote_field instead.
```

I went in and edited those lines to replace `field.rel` with `field.remote_field`, and it seems to have worked fine. But I don't know how to run the modelcluster test suite against that change to find out.

**Comment by gasman** [comment]
See https://github.com/wagtail/wagtail/issues/3599#issuecomment-302024843 - we'll make these changes at the point that we drop Django 1.8 support.
