### ISSUE TITLE
Django 2.0 support (dropping Django 1.8 support ?)

### ISSUE THREAD

**Issue by smendes** [wagtail/django-modelcluster#85]
We are using both Wagtail and ModelCluster on a project and after trying to run Django 2.0 Beta 1 I found some issues in ModelCluster.

I've made a few changes locally to make it run:
- `field.rel` -> `field.remote_field`  (in django.db.models.fields.Field)
- `field.rel.to` -> `field.remote_field.model`  (in django.db.models.fields.reverse_related.ForeignObjectRel)

Looking through the issues I've found your answer in [Wagtail's issue #3599](https://github.com/wagtail/wagtail/issues/3599). I was wondering if there are any plans to drop the support of Django 1.8 for ModelCluster and move forward with those changes.

And if that's the case I can provide a PR of those changes if you want.

**Comment by gasman** [comment]
Thanks for investigating this, @smendes! Yes, I think now is the time to drop Django 1.8 support in favour of 2.0. A PR would be very welcome.

**Comment by smendes** [comment]
PR opened #86 
To make it work it depends on an update of [django-taggit](https://github.com/alex/django-taggit/pull/509).

Also worth mentioning I've added an empty implementation of [`_apply_rel_filters`](https://github.com/wagtail/django-modelcluster/pull/86/files#diff-df087d1a0efd5a7deb55404a549ae3d7R69) that should be compatible with all versions but that can probably be done much better.

**Comment by gasman** [comment]
Completed in #86.
