### ISSUE TITLE
unique_together is not working in ClusterableModel

### ISSUE THREAD

**Issue by sowinski** [wagtail/django-modelcluster#88]
Hi,

is it possible to use the unique_together constraint somehow in a ClusterableModel?

Thank You!

**Comment by gasman** [comment]
Hi @sowinski,
Yes, support for unique constraints was added in the latest release - https://github.com/wagtail/django-modelcluster/pull/84
(If this doesn't cover what you need, please open a new issue describing the missing functionality.)

**Comment by sowinski** [comment]
HI @gasman,

thx for the fast response.

I've installed the latest version with pip (4.0) and it is still not working. Did I miss anything? 
This is my ClusterableModel.

```
@register_snippet
class NavigationMenu(ClusterableModel):
    FOOTERCOL1 = 'FC1'
    FOOTERCOL2 = 'FC2'
    FOOTERCOL3 = 'FC3'
    FOOTERCOL4 = 'FC4'
    MENU_CHOICES = (
        (FOOTERCOL1, 'Footer culumn 1'),
        (FOOTERCOL2, 'Footer culumn 2'),
        (FOOTERCOL3, 'Footer culumn 3'),
        (FOOTERCOL4, 'Footer culumn 4'),
    )

    objects         = NavigationMenuManager()
    menu_location   = models.CharField(null=False, max_length=255, help_text="Template name (do not change)", choices=MENU_CHOICES)
    site            = models.ForeignKey(Site, blank=True, null=True)
    menu_name       = models.CharField(null=True, blank=True, max_length=255)

    unique_together = ("site", "menu_location")
```

**Comment by gasman** [comment]
@sowinski Your definition is incorrect: `unique_together` needs to be inside a Meta class, and should be a list of tuples.

    @register_snippet
    class NavigationMenu(models.Model):
        FOOTERCOL1 = 'FC1'
        # ...
        class Meta:
            unique_together = [
                ("site", "menu_location"),
            ]
