### ISSUE TITLE
Missing 3.1 release and git tag

### ISSUE THREAD

**Issue by mojeto** [wagtail/django-modelcluster#91]
Hi,
I found out there is a release 3.1 on [pypi ](https://pypi.python.org/pypi/django-modelcluster/3.1) 
and in CHANGELOG https://github.com/wagtail/django-modelcluster/blob/63e2dc466afcef202ce2c91e3ce4139b6575dd35/CHANGELOG.txt#L15-L24

For some reason 3.1 release isn't on [github release page](https://github.com/wagtail/django-modelcluster/releases) and `v3.1` tag is missing.

Can we fix it please?

**Comment by gasman** [comment]
Added now - https://github.com/wagtail/django-modelcluster/releases/tag/v3.1
