### ISSUE TITLE
Searching for limit_choices_to for ParentalManyToManyField

### ISSUE THREAD

**Issue by tombreit** [wagtail/django-modelcluster#97]
For a plain Django many-to-many field exists an argument ``limit_choices_to``[1]. 

Is it possible  to have an argument like that for a modelcluster ``ParentalManyToManyField``?

Background is a wagtail project, were I would like to limit the choices for a ``ParentalManyToManyField`` to a specific value of the related model field (pseudocode):

```
# models.py
MyPage(Page):
    authors = ParentalManyToManyField(
        'profile.ProfilePage',
        blank=True,
        limit_choices_to={'is_author': True},
)
```

[1] https://docs.djangoproject.com/en/2.0/ref/models/fields/#django.db.models.ManyToManyField.limit_choices_to

**Comment by gasman** [comment]
Hi @tombreit,
What happens when you try adding a `limit_choices_to` argument? From a quick look at the code I can't immediately see anything that would prevent it from just working.

**Comment by tombreit** [comment]
Dear @gasman , 
you're totally right: it works as expected - I just referenced the wrong model... Sorry for the noise.
